import Head from "next/head";
import Image from "next/image";
import lukasz from "../public/avatar-lukasz.png";
import mars from "../public/mars.svg";
import bain from "../public/bain.svg";
import deloitte from "../public/deloitte.svg";
import novo from "../public/novo-nordisk.svg";
import mf from "../public/mf.svg";
import euronet from "../public/euronet.svg";
import portfolio from "../public/portfolio.png";
import { AiFillLinkedin } from "react-icons/ai";
import { useRouter } from "next/router";
import Section from "../components/ui/section";
import Title from "../components/ui/title";
import NewTimeline from "../components/ui/newtimeline";

export default function Home() {
  const router = useRouter();

  const handlePortfolioClick = () => {
    router.push("/portfolio");
  };

  return (
    <div>
      <Head>
        <title>Lukasz Filipiuk</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
        <link rel="preconnect" href="https://fonts.googleapis.com" />
        <link rel="preconnect" href="https://fonts.gstatic.com" />
        <link
          href="https://fonts.googleapis.com/css2?family=Inter:wght@400;500;600;700&family=Newsreader:opsz,wght@6..72,500&display=swap"
          rel="stylesheet"
        />
      </Head>

      <main className={"bg-gray-900 font-inter my-32"}>
        <Section>
          <header className={"flex items-center justify-between"}>
            <div className={"flex"}>
              <div
                className={
                  "bg-gradient-to-b from-teal-500 rounded-full w-16 h-16 relative overflow-hidden"
                }
              >
                <Image
                  src={lukasz}
                  alt={"Picture of me"}
                  width={200}
                  height={200}
                />
              </div>
              <div className={"px-4"}>
                <p className={"text-white font-newsreader text-2xl"}>
                  Łukasz Filipiuk
                </p>
                <p className={"text-xl text-gray-500"}>Some text goes here</p>
              </div>
            </div>
            <div className={"text-gray-600 hover:text-gray-200 text-4xl"}>
              <a href={"https://www.linkedin.com/in/lfilipiuk/"}>
                <AiFillLinkedin />
              </a>
            </div>
          </header>
        </Section>

        <Section>
          <Title name={"about me"} />
          <p className={"leading-7 text-gray-100"}>
            Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do
            eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim
            ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut
            aliquip Ut enim ad minim veniam, quis nostrud exercitation ullamco
            laboris.
          </p>
        </Section>

        <Section>
          <Title name={"i taught at"} />

          <div className={"flex flex-wrap gap-2 items-center"}>
            <div className={"flex-auto"}>
              <Image src={euronet} alt={"Euronet Logo"} />
            </div>
            <div className={"flex-auto"}>
              <Image src={bain} alt={"Bain & Company Logo"} />
            </div>
            <div className={"flex-auto"}>
              <Image src={mars} alt={"Mars Logo"} />
            </div>
            <div className={"flex-auto"}>
              <Image src={novo} alt={"Novo Nordisk Logo"} />
            </div>
            <div className={"flex-auto"}>
              <Image src={mf} alt={"Ministry of Finance Logo"} />
            </div>
            <div className={"flex-auto"}>
              <Image src={deloitte} alt={"Deloitte Logo"} />
            </div>
          </div>
        </Section>

        <Section>
          <Title name={"portfolio"} />

          <div
            className={
              "transition ease-in-out hover:-translate-y-1 hover:shadow-xl duration-200 cursor-pointer pt-2"
            }
            onClick={handlePortfolioClick}
          >
            <Image
              className={"rounded-lg object-cover"}
              width={700}
              height={200}
              src={portfolio}
              alt={"Portfolio image"}
            />
          </div>
        </Section>

        <Section>
          <Title name={"my experience"} />
          <NewTimeline />
        </Section>

        <Section>
          <Title name={"what others say about me"} />
          <div className={"text-white italic text-gray-400 py-2 leading-7"}>
            <p>
              “I am once again very impressed with the{" "}
              <span className={"font-bold text-gray-200"}>
                knowledge and preparation
              </span>{" "}
              as well as the PASSION with which the Leaders convey this
              knowledge to the Participants“
            </p>
          </div>
          <div className={"text-white italic text-gray-400 py-3 leading-7"}>
            <p>
              “The teacher was very well-prepared,{" "}
              <span className={"font-bold text-gray-200"}>
                presented the discussed tools in an accessible
              </span>{" "}
              way and helped course participants in the event of problems with
              taking the &quot;step by step&quot; approach.“
            </p>
          </div>
          <div className={"text-white italic text-gray-400 py-3 leading-7"}>
            <p>
              “Łukasz has good contact with the course participants, he explains
              the material very well, he can answer any question and{" "}
              <span className={"font-bold text-gray-200"}>
                keep the participants active
              </span>{" "}
              despite the long training day.“
            </p>
          </div>
        </Section>
      </main>
    </div>
  );
}
